### PR TITLE
Spo sharing settings

### PR DESCRIPTION
**Pull request by ThorstenLoeschmann**
#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/office365dsc/47)

### CODE REVIEW

**Comment by ykuijs** [comment]
Oh and this resource does not have any Pester tests, so the code coverage currently is very low. Please add a Pester test as well.

**Comment by ThorstenLoeschmann** [comment]
Thank you for the input. I already fixed most of the style related findings and will also write some Pester tests. Regarding the Tenant property, Nik previously highlighted this to me, but since I needed a key property I kept the Tenant, since I had no better idea to be honest... What would be the preferred way of doing it? Thank you

**Comment by ykuijs** [comment]
Since this resource should only be used once in each configuration (to prevent conflicts), I would implement the IsSingleInstance solution as described here: https://docs.microsoft.com/en-us/powershell/dsc/resources/singleinstance

For examples, please check SPInstall in SharePointDsc: https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.schema.mof#L4

**Comment by ThorstenLoeschmann** [comment]
I was wondering, if there is still anything missing on this one?

**Comment by NikCharlebois** [comment]
Waiting on you to respond/acknowledge to the comments in Reviewable before it gets to us for merging

**Comment by NikCharlebois** [comment]
@ykuijs I believe this one is also pending your final blessing.

**Pull request merged**
