### PR TITLE
Fixes Issue #277

### LINKED ISSUE #277: SCDLPComplianceRule is not working correctly
#### Details of the scenario you tried and the problem that is occurring
the issue is related to ReverseDSC and Export-O365Configuration.. When creating a policy rule with a condition 'All of these' the data returned is invalid because the **ContentContainsSensitiveInformation** structure is different.
And even in the case of 'Any of these' only one condition per rule is returned.
  
#### Suggested solution to the issue
Not sure, a bit of restructuring in the DSC resource shemas could be required because apart from the conditions we would also like to know about the operator used.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Not available. 
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fixed an issue where extraction failed if the name of the Sensitive Information property contained apostrophes;

#### This Pull Request (PR) fixes the following issues
- Fixes #277

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/office365dsc/341)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs Another small one for review. Thanks

**Comment by NikCharlebois** [comment]
Also linked to #258

**Comment by NikCharlebois** [comment]
@ykuijs ready for next round of review. Typo fixed

**Comment by ykuijs** [comment]
Finally Reviewable found some time to process the approval ;-)

**Pull request merged**
