### PR TITLE
New Resource O365OrgCustomizationSetting

### LINKED ISSUE #136: O365OrgCustomizationSettings
### Description
When trying to configure Security and Compliance components for the first time on certain tenants, you will get the following error back:

_The command you tried to run isn't currently allowed in your organization. To run this        command, you first need to run the command: Enable-OrganizationCustomization.                     + CategoryInfo          : NotSpecified: (Microsoft.Excha...AntiPhishPolicy:) [], CimExce     ption                                                                                          + FullyQualifiedErrorId : [Server=YQBPR0101MB0851,RequestId=4feee150-d5e9-4d98-aaa2-c8e4     33c8bb8b,TimeStamp=7/5/2019 1:01:17 PM] [FailureCategory=Cmdlet-InvalidOperationInDehydr     atedContextException] FDC3D516,Microsoft.Exchange.Management.SystemConfigurationTasks.Ne     wAntiPhishPolicy                                                                                 + PSComputerName        : Localhost_

It would be useful to have a resource to handle the enabling of OrganizationCustomization, which would run Enable-OrganizationCustomization in the background.

### Proposed properties
- IsSingleInstance
- Enabled [$true|$false]

### Special considerations or limitations
There doesn't seem to be the equivalent Disable cmdlet, therefore we may want to prevent Enabled = $false

### PR DESCRIPTION
**Pull request by andikrueger**
#### Pull Request (PR) description
Created new resource O365OrgCustomizationSetting.

#### This Pull Request (PR) fixes the following issues
    - Fixes #136 

@NikCharlebois actually, I do not know if the Export-Target Resource is implemented correctly. There is no need to create a resource for a setting, that is one-way only.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/office365dsc/231)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@andikrueger It may not expose an update setting, but it still defines a State, that is that customization is enabled or not. We just don't need to expose the Ensure parameter, and do IsSingleInstance='yes'

**Comment by andikrueger** [comment]
@NikCharlebois Will change the resource accordingly.

**Comment by NikCharlebois** [comment]
I will let you resolve the merge conflicts on your end

**Comment by andikrueger** [comment]
I'm on it...

**Comment by NikCharlebois** [comment]
@andikrueger any updates on the Unit tests? Need help with something? Thanks

**Comment by andikrueger** [comment]
@NikCharlebois Could you have a look at the errors? I feel, it's not my unit test, that fails.

**Comment by NikCharlebois** [comment]
Looks like you are missing a new line  character ' `' on line 16 of the tests

**Comment by andikrueger** [comment]
Thanks for finding this glitch. I will fix it. Rebasing was a nightmare.

**Comment by andikrueger** [comment]
Current error is thrown by 'TeamsClientConfiguration' or at least I hope it is ;-)

**Pull request merged**
