### PR TITLE
Various Fixes

### LINKED ISSUE #278: SPOSiteDesignRights Rights property is invalid
#### Details of the scenario you tried and the problem that is occurring
I tried to export the site design rights but could not create the mof file. When calling Office365TenantConfig.ps1
i got the following error:
```
Office365DSC\SPOSiteDesignRights : At least one of the values 'System.Object[]' is not supported or valid for property
'Rights' on class 'SPOSiteDesignRights'. Please specify only supported values:
View, None.
At C:\temp\tstsitedesign\Office365TenantConfig.ps1:30 char:9
+         SPOSiteDesignRights c3e1fe9f-ed3e-44ed-8725-5b73f37fa360
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Office365DSC\SPOSiteDesignRights

Compilation errors occurred while processing configuration 'O365TenantConfig'. Please review the errors reported in
error stream and modify your configuration code appropriately.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (O365TenantConfig:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
```
#### Verbose logs showing the problem
```
Office365DSC\SPOSiteDesignRights : At least one of the values 'System.Object[]' is not supported or valid for property
'Rights' on class 'SPOSiteDesignRights'. Please specify only supported values:
View, None.
At C:\temp\tstsitedesign\Office365TenantConfig.ps1:30 char:9
+         SPOSiteDesignRights c3e1fe9f-ed3e-44ed-8725-5b73f37fa360
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Office365DSC\SPOSiteDesignRights

Compilation errors occurred while processing configuration 'O365TenantConfig'. Please review the errors reported in
error stream and modify your configuration code appropriately.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917
char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (O365TenantConfig:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

  SPOSiteDesignRights 158e9200-5cfc-4c17-aa6f-bbef0517cad7
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Rights               = "System.Object[]";
            SiteDesignTitle      = "My Company Design #2";
            UserPrincipals       = @("meganb@m365x233468.onmicrosoft.com","nestorw@m365x233468.onmicrosoft.com");
        }


```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### LINKED ISSUE #279: SCSensitivityLabel information is not exported in O365DSCReverse
#### Details of the scenario you tried and the problem that is occurring
We noticed that SCSensitivityLabel resources are not included in the resulting ps1 file.
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### LINKED ISSUE #290: TeamsUser User property is not correctly extracted
#### Details of the scenario you tried and the problem that is occurring

```powershell
 Export-O365Configuration -ComponentsToExtract @("chckTeamsUser") -Quiet
```
The username in the generated mof file is wrong:
```
instance of MSFT_TeamsUser as $MSFT_TeamsUser8ref
{
ResourceID = "[TeamsUser]44302c47-8697-4089-8cd7-aacfc9fbe56a";
 Ensure = "Present";
 Role = "Member";
 User = "PradeepG@M365x233468.onmicrosoft.com.OnMicrosoft.com";
 GlobalAdminAccount = $MSFT_Credential8ref;
 SourceInfo = "C:\\temp\\test0612_5\\Office365TenantConfig.ps1::86::9::TeamsUser";
 ModuleName = "Office365DSC";
 ModuleVersion = "1.0.0.1048";
 TeamName = "Sales and Marketing";

 ConfigurationName = "O365TenantConfig";

};
```
The problem is that the onmicrosoft.com part repeats itself and is an invalid username.
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### LINKED ISSUE #291: TeamsUser telemetry is causing problems during extraction
#### Details of the scenario you tried and the problem that is occurring
The extraction process for TeamsUser resources fails unless i remove the call to the telemetry engine
#### Verbose logs showing the problem
The term 'Add-O365DSCTelemetryEvent' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
#### Suggested solution to the issue
i think that this is just a matter of a missing import since the users are extracted in parallel jobs.
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fixes

#### This Pull Request (PR) fixes the following issues
- Fixes #290 

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/office365dsc/293)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs for your review #1

**Comment by NikCharlebois** [comment]
No, others have been fixed in previous PRs. My bad. It simply fixes #290

**Comment by ykuijs** [comment]
No update to the changelog?

**Comment by NikCharlebois** [comment]
Good catch. Changelog updated

**Pull request merged**
