### PR TITLE
Added new SCComplianceCase (for eDiscovery) Resource

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Adds a new SCComplianceCase resource to create eDiscovery Cases

#### This Pull Request (PR) fixes the following issues
N/A

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/office365dsc/189)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs Full-Circle Tests are broken for the moment (actually they now work as expected). Please don't let these prevent you from doing a Code Review. Cheers mate.

**Comment by NikCharlebois** [comment]
@ykuijs all your to review mate

**Comment by ykuijs** [comment]
Somehow your latest commit broke a lot of tests, some not even related to your update.

**Comment by ykuijs** [comment]
I think this was caused by the PR of Brian you just merged

**Comment by NikCharlebois** [comment]
Yes, tests are in limbo until this PR is merged. Code Review all good on you end? Ready for me to merge?

**Comment by ykuijs** [comment]
Reviewable again has issues. Can't approve. I am fine with the changes.

**Pull request merged**
